/* !
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This file is generated by ascendc-ir. DO NOT EDIT MANUALLY.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include "c_api/asc_simd.h"

__simd_vf__ inline void arange_vf(
    __ubuf__ float* dst, uint32_t data_len, float start_value)
{
    uint16_t one_rep_size = asc_get_vf_len() / sizeof(float);
    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;

    vector_bool vmask = asc_create_mask_b32(PAT_ALL);
    vector_float reg_dst;
    for (uint16_t i = 0; i < repeat_time; ++i) {
        asc_arange(reg_dst, start_value);
        asc_storealign(dst + i * one_rep_size, reg_dst, vmask);
        start_value += static_cast<float>(one_rep_size);
    }
}

__vector__ __global__ __aicore__ void op_arange(__gm__ float* z)
{
    asc_init();

    __ubuf__ float buf_0[64];

    arange_vf(buf_0, 64, 0.0f);
    asc_sync_notify(PIPE_V, PIPE_MTE3, EVENT_ID0);
    asc_sync_wait(PIPE_V, PIPE_MTE3, EVENT_ID0);
    asc_copy_ub2gm(z, buf_0, 1, 256, 0, 0);
}

#include "op_arange_launch.h"

extern "C" void launch_op_arange(GM_ADDR z, void* stream)
{
    op_arange<<<1, 0, stream>>>((__gm__ float*)z);
}
