/* !
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This file is generated by ascendc-ir. DO NOT EDIT MANUALLY.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include "c_api/asc_simd.h"

__simd_vf__ inline void select_le_vf(
    __ubuf__ float* src0, __ubuf__ float* src1, __ubuf__ float* dst, uint32_t data_len)
{
    uint16_t one_rep_size = asc_get_vf_len() / sizeof(float);
    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;

    vector_bool vmask;
    vector_bool cmp_mask;
    vector_float reg_src0;
    vector_float reg_src1;
    vector_float reg_dst;
    for (uint16_t i = 0; i < repeat_time; ++i) {
        vmask = asc_update_mask_b32(data_len);
        asc_loadalign(reg_src0, src0 + i * one_rep_size);
        asc_loadalign(reg_src1, src1 + i * one_rep_size);
        asc_le(cmp_mask, reg_src0, reg_src1, vmask);
        asc_select(reg_dst, reg_src0, reg_src1, cmp_mask);
        asc_storealign(dst + i * one_rep_size, reg_dst, vmask);
    }
}

__vector__ __global__ __aicore__ void op_select_le(__gm__ float* x, __gm__ float* y, __gm__ float* z)
{
    asc_init();

    __ubuf__ float buf_0[64];
    __ubuf__ float buf_1[64];
    __ubuf__ float buf_2[64];

    asc_copy_gm2ub(buf_0, x, 1, 256, 0, 0);
    asc_copy_gm2ub(buf_1, y, 1, 256, 0, 0);
    asc_sync_notify(PIPE_MTE2, PIPE_V, EVENT_ID0);
    asc_sync_wait(PIPE_MTE2, PIPE_V, EVENT_ID0);
    select_le_vf(buf_0, buf_1, buf_2, 64);
    asc_sync_notify(PIPE_V, PIPE_MTE3, EVENT_ID0);
    asc_sync_wait(PIPE_V, PIPE_MTE3, EVENT_ID0);
    asc_copy_ub2gm(z, buf_2, 1, 256, 0, 0);
}

#include "op_select_le_launch.h"

extern "C" void launch_op_select_le(GM_ADDR x, GM_ADDR y, GM_ADDR z, void* stream)
{
    op_select_le<<<1, 0, stream>>>((__gm__ float*)x, (__gm__ float*)y, (__gm__ float*)z);
}
