# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

"""代码生成：Kernel 模型 → 调用 C API 的 .asc 源码。

生成规则：
- 先跑检查器，存在 block 诊断即拒绝生成（fail closed）。
- event 分配：每逻辑通道一个 EVENT_ID（前向 sync 一条通道；WAR 释放每 buffer 一条通道）。
- WAR 释放边由 stages 推导：复用槽位前 `if (i >= N) wait(消费, 生产)`；
  消费完成后 `if (i + N < TILES) notify(消费, 生产)`。
- 计算 op 只支持已核对头文件签名的映射（当前：add）；其余拒绝生成。
- v0.2 不生成多核切分（无 asc_get_block_idx 词汇，见 vocabulary-evidence.md gap）。
"""

from __future__ import annotations

from ..devices import load_device
from ..model.core import BufRef, GmRef, Pipe
from ..model.stmts import ComputeStmt, CopyStmt, SyncStmt
from ..verify import verify
from .reroll import reroll

_REPEAT_BYTES = 256
_BLOCK_BYTES = 32

_DTYPE_TO_C = {"f16": "half", "f32": "float"}
_PIPE_TO_C = {
    Pipe.S: "PIPE_S",
    Pipe.V: "PIPE_V",
    Pipe.M: "PIPE_M",
    Pipe.MTE1: "PIPE_MTE1",
    Pipe.MTE2: "PIPE_MTE2",
    Pipe.MTE3: "PIPE_MTE3",
    Pipe.FIX: "PIPE_FIX",
}

_SUPPORTED_COMPUTE = {"add"}

_LICENSE = """/* !
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This file is generated by ascendc-ir. DO NOT EDIT MANUALLY.
 * See LICENSE in the root of the software repository for the full text of the License.
 */"""


class CodegenError(Exception):
    pass


def generate(kernel, device=None) -> str:
    dev = device if device is not None else load_device(kernel.device)
    blocks = [d for d in verify(kernel, dev) if d.severity == "block"]
    if blocks:
        detail = "; ".join(f"{d.id}@{d.callsite.line}: {d.message}" for d in blocks)
        raise CodegenError(f"检查器拒绝生成：{detail}")
    tiles, body, ok = reroll(kernel)
    if not ok:
        raise CodegenError(
            f"循环重卷失败：trace 展开的 {len(kernel.statements)} 条语句不满足仿射规律（tiles={tiles}）。"
            "请保持循环体语句一致、GM 偏移关于 i 仿射、buffer 槽位为 i % stages"
        )
    return _Emitter(kernel, dev, tiles, body).emit()


class _Emitter:
    def __init__(self, kernel, device, tiles, body):
        self.kernel = kernel
        self.device = device
        self.tiles = tiles
        self.body = body
        self.looped = tiles > 1
        self.per = len(kernel.statements) // tiles
        self._events = {}
        self._war = self._analyze_war()

    # ---- 分析 ----

    def _analyze_war(self):
        """每 buffer 的生产/消费 PIPE；跨 PIPE 的 buffer 需要 WAR 通道。"""
        war = {}
        for buf in self.kernel.buffers:
            writers, readers = set(), set()
            for stmt in self.kernel.statements:
                if isinstance(stmt, CopyStmt):
                    if isinstance(stmt.dst, BufRef) and stmt.dst.buffer is buf:
                        writers.add(stmt.pipe)
                    if isinstance(stmt.src, BufRef) and stmt.src.buffer is buf:
                        readers.add(stmt.pipe)
                elif isinstance(stmt, ComputeStmt):
                    if stmt.dst.buffer is buf:
                        writers.add(stmt.pipe)
                    for s in stmt.srcs:
                        if isinstance(s, BufRef) and s.buffer is buf:
                            readers.add(stmt.pipe)
            if len(writers) == 1 and len(readers) == 1:
                p, q = next(iter(writers)), next(iter(readers))
                if p != q:
                    war[buf.name] = (p, q)
            elif writers or readers:
                raise CodegenError(f"buffer {buf.name} 有多个生产/消费 PIPE，v0.2 不支持")
        return war

    def _event(self, key) -> str:
        if key not in self._events:
            if len(self._events) >= self.device.event_ids:
                raise CodegenError(f"event 通道数超过 event_ids={self.device.event_ids}")
            self._events[key] = f"EVENT_ID{len(self._events)}"
        return self._events[key]

    # ---- 引用表达式 ----

    def _buf_ptr(self, ref: BufRef) -> str:
        buf = ref.buffer
        if not self.looped or buf.stages == 1:
            return buf.name
        return f"{buf.name} + (i % {buf.stages}) * {buf.elems}"

    def _gm_ptr(self, ref: GmRef, stmt_index: int, ref_index: int) -> str:
        if not self.looped:
            return ref.param.name if ref.offset == 0 else f"{ref.param.name} + {ref.offset}"
        stride = self._gm_stride(stmt_index, ref_index)
        if stride == 0:
            return ref.param.name
        return f"{ref.param.name} + i * {stride}"

    def _gm_stride(self, stmt_index: int, ref_index: int) -> int:
        """同一语句在第 1 轮的 GM 偏移减第 0 轮（reroll 已验证仿射）。"""
        first = _stmt_refs(self.kernel.statements[stmt_index])[ref_index]
        second = _stmt_refs(self.kernel.statements[self.per + stmt_index])[ref_index]
        return second.offset - first.offset

    # ---- 发射 ----

    def emit(self) -> str:
        k = self.kernel
        lines = [_LICENSE, "", '#include "c_api/asc_simd.h"', ""]
        params = ", ".join(f"__gm__ {_DTYPE_TO_C[p.dtype.value]}* {p.name}" for p in k.params)
        lines.append(f"__vector__ __global__ __aicore__ void {k.name}({params})")
        lines.append("{")
        lines.append("    asc_init();")
        lines.append("")
        for buf in k.buffers:
            c_type = _DTYPE_TO_C[buf.dtype.value]
            lines.append(f"    __ubuf__ {c_type} {buf.name}[{buf.stages} * {buf.elems}];")
        lines.append("")
        body_lines = []
        for j, stmt in enumerate(self.body):
            body_lines.extend(self._emit_stmt(stmt, j))
        if self.looped:
            lines.append(f"    for (uint32_t i = 0; i < {self.tiles}; i++) {{")
            lines.extend("        " + line for line in body_lines)
            lines.append("    }")
        else:
            lines.extend("    " + line for line in body_lines)
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def _emit_stmt(self, stmt, j: int) -> list:
        if isinstance(stmt, CopyStmt):
            return self._emit_copy(stmt, j)
        if isinstance(stmt, ComputeStmt):
            return self._emit_compute(stmt, j)
        if isinstance(stmt, SyncStmt):
            return self._emit_sync(stmt)
        raise CodegenError(f"未知语句类型 {type(stmt).__name__}")

    def _war_wait(self, buf) -> list:
        """复用槽位前等待消费方完成。"""
        if buf.name not in self._war or not self.looped or self.tiles <= buf.stages:
            return []
        p, q = self._war[buf.name]
        ev = self._event(("war", buf.name))
        return [f"if (i >= {buf.stages}) {{ asc_sync_wait({_PIPE_TO_C[q]}, {_PIPE_TO_C[p]}, {ev}); }}"]

    def _war_notify(self, buf) -> list:
        """消费完成后释放槽位给生产方。"""
        if buf.name not in self._war or not self.looped or self.tiles <= buf.stages:
            return []
        p, q = self._war[buf.name]
        ev = self._event(("war", buf.name))
        return [f"if (i + {buf.stages} < {self.tiles}) {{ asc_sync_notify({_PIPE_TO_C[q]}, {_PIPE_TO_C[p]}, {ev}); }}"]

    def _emit_copy(self, stmt: CopyStmt, j: int) -> list:
        if stmt.pipe == Pipe.MTE2 and isinstance(stmt.src, GmRef) and isinstance(stmt.dst, BufRef):
            buf = stmt.dst.buffer
            lines = self._war_wait(buf)
            lines.append(
                f"asc_copy_gm2ub({self._buf_ptr(stmt.dst)}, {self._gm_ptr(stmt.src, j, 0)}, 1, {_burst(buf)}, 0, 0);"
            )
            return lines
        if stmt.pipe == Pipe.MTE3 and isinstance(stmt.src, BufRef) and isinstance(stmt.dst, GmRef):
            buf = stmt.src.buffer
            lines = [f"asc_copy_ub2gm({self._gm_ptr(stmt.dst, j, 1)}, {self._buf_ptr(stmt.src)}, 1, {_burst(buf)}, 0, 0);"]
            lines.extend(self._war_notify(buf))
            return lines
        raise CodegenError(f"v0.2 不支持的 copy 形态：pipe={stmt.pipe.value}")

    def _emit_compute(self, stmt: ComputeStmt, j: int) -> list:
        if stmt.op not in _SUPPORTED_COMPUTE:
            raise CodegenError(f"v0.2 代码生成只支持 {sorted(_SUPPORTED_COMPUTE)}，得到 {stmt.op!r}（trace/verify 可用）")
        dst = stmt.dst
        if dst.buffer.stage_bytes % _REPEAT_BYTES != 0:
            raise CodegenError(
                f"buffer {dst.buffer.name} 单 stage {dst.buffer.stage_bytes}B 不是 {_REPEAT_BYTES}B 的整数倍，无法计算 repeat"
            )
        repeat = dst.buffer.stage_bytes // _REPEAT_BYTES
        lines = self._war_wait(dst.buffer)
        ptrs = [self._buf_ptr(dst)] + [self._buf_ptr(s) for s in stmt.srcs]
        lines.append(f"asc_add({ptrs[0]}, {ptrs[1]}, {ptrs[2]}, {repeat}, 1, 1, 1, 8, 8, 8);")
        for s in stmt.srcs:
            lines.extend(self._war_notify(s.buffer))
        return lines

    def _emit_sync(self, stmt: SyncStmt) -> list:
        ev = self._event(("fwd", stmt.producer.value, stmt.consumer.value, tuple(sorted(b.name for b in stmt.on))))
        p, q = _PIPE_TO_C[stmt.producer], _PIPE_TO_C[stmt.consumer]
        return [f"asc_sync_notify({p}, {q}, {ev});", f"asc_sync_wait({p}, {q}, {ev});"]


def _burst(buf) -> int:
    if buf.stage_bytes % _BLOCK_BYTES != 0:
        raise CodegenError(f"buffer {buf.name} 单 stage {buf.stage_bytes}B 不是 {_BLOCK_BYTES}B 的整数倍")
    return buf.stage_bytes // _BLOCK_BYTES


def _stmt_refs(stmt) -> list:
    if isinstance(stmt, CopyStmt):
        return [stmt.src, stmt.dst]
    if isinstance(stmt, ComputeStmt):
        return [stmt.dst] + list(stmt.srcs)
    return []
