# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

"""代码生成：Kernel 模型 → 调用 C API 的 .asc 源码。

生成规则：
- 先跑检查器，存在 block 诊断即拒绝生成（fail closed）。
- event 分配（ADR 0010/0011）：event id 按 (生产PIPE, 消费PIPE) 对独立分配，且全部为
  字面量。循环按流水深度展开，同一 id 上 notify/wait 严格交替；TILES 不能被流水深度整除时拒绝生成。
- 软件流水（ADR 0013，M0 的去守卫通过线）：把循环切成 prologue / 稳态 / epilogue。
  稳态里的 WAR wait 与 notify 都是无条件指令，不再生成 `if (i >= N)`。
- WAR 释放边由 stages 推导：复用槽位前 wait（消费, 生产），**该槽位在循环体内的
  最后一次消费之后**才 notify（复审 2026-09-26 第 1 条）；同一语句重复读同一
  buffer 只释放一次。
- 计算 op 只支持已核对头文件签名的映射（当前：add）；其余拒绝生成。
- v0.2 不生成多核切分；不支持跨 PIPE 就地改写（一个 buffer 的生产 PIPE 必须唯一）。
"""

from __future__ import annotations

import math

from ..devices import load_device
from ..model.core import BufRef, GmRef, Pipe
from ..model.stmts import ComputeStmt, CopyStmt, SyncStmt
from ..verify import verify
from .reroll import reroll

_REPEAT_BYTES = 256
_REPEAT_MAX = 255  # asc_add 的 repeat 是 uint8_t
_BLOCK_BYTES = 32

_DTYPE_TO_C = {"f16": "half", "f32": "float"}
_PIPE_TO_C = {
    Pipe.S: "PIPE_S",
    Pipe.V: "PIPE_V",
    Pipe.M: "PIPE_M",
    Pipe.MTE1: "PIPE_MTE1",
    Pipe.MTE2: "PIPE_MTE2",
    Pipe.MTE3: "PIPE_MTE3",
    Pipe.FIX: "PIPE_FIX",
}

_SUPPORTED_COMPUTE = {"add"}

_LICENSE = """/* !
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This file is generated by ascendc-ir. DO NOT EDIT MANUALLY.
 * See LICENSE in the root of the software repository for the full text of the License.
 */"""


class CodegenError(Exception):
    pass


def generate(kernel, device=None) -> str:
    dev = device if device is not None else load_device(kernel.device)
    blocks = [d for d in verify(kernel, dev) if d.severity == "block"]
    if blocks:
        detail = "; ".join(f"{d.id}@{d.callsite.line}: {d.message}" for d in blocks)
        raise CodegenError(f"检查器拒绝生成：{detail}")
    tiles, body, ok = reroll(kernel)
    if not ok:
        raise CodegenError(
            f"循环重卷失败：trace 展开的 {len(kernel.statements)} 条语句不满足仿射规律，"
            "或存在无循环标记的槽位复用。循环体内的 sync 必须写 stage=迭代号；"
            "循环体语句保持一致、GM 偏移关于 i 仿射、buffer 槽位为 i % stages"
        )
    return _Emitter(kernel, dev, tiles, body).emit()


class _Emitter:
    def __init__(self, kernel, device, tiles, body):
        self.kernel = kernel
        self.device = device
        self.tiles = tiles
        self.body = body
        self.looped = tiles > 1
        self.per = len(kernel.statements) // tiles
        self._pair_events = {}  # (set_pipe, wait_pipe) -> {channel_key: base_id}
        self._pair_used = {}  # (set_pipe, wait_pipe) -> int
        self._war = self._analyze_war()
        self._last_read = self._analyze_last_reads()
        self._unroll = self._unroll_factor()

    # ---- 分析 ----

    def _analyze_war(self):
        """每 buffer 的生产/消费 PIPE；跨 PIPE 的 buffer 需要 WAR 通道。"""
        war = {}
        for buf in self.kernel.buffers:
            writers, readers = set(), set()
            for stmt in self.kernel.statements:
                if isinstance(stmt, CopyStmt):
                    if isinstance(stmt.dst, BufRef) and stmt.dst.buffer is buf:
                        writers.add(stmt.pipe)
                    if isinstance(stmt.src, BufRef) and stmt.src.buffer is buf:
                        readers.add(stmt.pipe)
                elif isinstance(stmt, ComputeStmt):
                    if isinstance(stmt.dst, BufRef) and stmt.dst.buffer is buf:
                        writers.add(stmt.pipe)
                    for s in stmt.srcs:
                        if isinstance(s, BufRef) and s.buffer is buf:
                            readers.add(stmt.pipe)
            if len(writers) == 1 and len(readers) == 1:
                p, q = next(iter(writers)), next(iter(readers))
                if p != q:
                    war[buf.name] = (p, q)
            elif writers or readers:
                raise CodegenError(
                    f"buffer {buf.name} 有多个生产/消费 PIPE（{sorted(p.value for p in writers)} / "
                    f"{sorted(p.value for p in readers)}），v0.2 不支持跨 PIPE 就地改写；"
                    "请读旧 buffer、写新 buffer"
                )
        return war

    def _analyze_last_reads(self):
        """每个 buffer 在循环体内最后一次被读的语句下标（WAR 释放点，复审第 1 条）。"""
        last = {}
        for j, stmt in enumerate(self.body):
            for ref in _stmt_reads(stmt):
                last[ref.buffer.name] = j
        return last

    def _unroll_factor(self) -> int:
        """循环按各 buffer 流水深度的最小公倍数展开；TILES 须被整除。"""
        if not self.looped:
            return 1
        factor = 1
        for buf in self.kernel.buffers:
            factor = math.lcm(factor, buf.stages)
        if self.tiles % factor != 0:
            raise CodegenError(
                f"循环轮数 {self.tiles} 不能被流水深度 {factor} 整除，无法按槽位展开；"
                "请调整 TILES 或 stages"
            )
        return factor

    # ---- event 分配（按 PIPE 对独立，全部字面量）----

    def _alloc(self, pair, key, n: int = 1) -> int:
        channels = self._pair_events.setdefault(pair, {})
        if key in channels:
            return channels[key]
        used = self._pair_used.get(pair, 0)
        if used + n > self.device.event_ids:
            raise CodegenError(
                f"PIPE 对 {pair[0].value}→{pair[1].value} 上 event 通道需要 {used + n} 个 id，"
                f"超过每对 PIPE 的 event_ids={self.device.event_ids}"
            )
        channels[key] = used
        self._pair_used[pair] = used + n
        return used

    def _war_event_id(self, buf, producer: Pipe, consumer: Pipe, k: int) -> str:
        """WAR 通道按槽位一个字面量 id，保证同一 id 上 notify/wait 严格交替。"""
        base = self._alloc((consumer, producer), ("war", buf.name), buf.stages)
        return f"EVENT_ID{base + k % buf.stages}"

    # ---- 引用表达式（k 为展开后的子迭代号，槽位与偏移均为字面量/仿射式）----

    def _buf_ptr(self, ref: BufRef, k: int) -> str:
        buf = ref.buffer
        if buf.stages == 1:
            return buf.name
        # 直写形态每条语句自带槽位。循环形态的 body 是第 0 轮，槽位由展开下标 k 决定。
        slot = ref.stage if not self.looped else k % buf.stages
        return buf.name if slot == 0 else f"{buf.name} + {slot * buf.elems}"

    def _gm_ptr(self, ref: GmRef, stmt_index: int, ref_index: int, k: int, i_value) -> str:
        base = ref.offset  # body 是第 0 轮，offset 即基址
        if not self.looped:
            return ref.param.name if base == 0 else f"{ref.param.name} + {base}"
        stride = self._gm_stride(stmt_index, ref_index)
        if i_value is not None:
            offset = base + (i_value + k) * stride
            return ref.param.name if offset == 0 else f"{ref.param.name} + {offset}"
        if stride == 0:
            return ref.param.name if base == 0 else f"{ref.param.name} + {base}"
        term = f"i * {stride}" if k == 0 else f"(i + {k}) * {stride}"
        if base == 0:
            return f"{ref.param.name} + {term}"
        return f"{ref.param.name} + {base} + {term}"

    def _gm_stride(self, stmt_index: int, ref_index: int) -> int:
        first = _stmt_refs(self.kernel.statements[stmt_index])[ref_index]
        second = _stmt_refs(self.kernel.statements[self.per + stmt_index])[ref_index]
        return second.offset - first.offset

    # ---- 软件流水：同一段里 WAR 的有无必须对每个 i 都一样，才能不写 if ----

    def _signature(self, group_start: int) -> tuple:
        items = []
        for buf in self.kernel.buffers:
            if buf.name not in self._war or self.tiles <= buf.stages:
                continue
            for k in range(self._unroll):
                gi = group_start + k
                wait = "emit" if gi >= buf.stages else "omit"
                notify = "emit" if gi + buf.stages < self.tiles else "omit"
                items.append((buf.name, k, wait, notify))
        return tuple(items)

    def _regions(self) -> list:
        starts = list(range(0, self.tiles, self._unroll))
        regions = []
        index = 0
        while index < len(starts):
            signature = self._signature(starts[index])
            end = index + 1
            while end < len(starts) and self._signature(starts[end]) == signature:
                end += 1
            lo = starts[index]
            hi = starts[end - 1] + self._unroll
            regions.append((lo, hi, signature))
            index = end
        return regions

    def _war_decision(self, signature, buf, k: int, which: str) -> str:
        for name, slot, wait, notify in signature:
            if name == buf.name and slot == k:
                return wait if which == "wait" else notify
        return "omit"

    # ---- 发射 ----

    def emit(self) -> str:
        k = self.kernel
        lines = [_LICENSE, "", '#include "c_api/asc_simd.h"', ""]
        params = ", ".join(f"__gm__ {_DTYPE_TO_C[p.dtype.value]}* {p.name}" for p in k.params)
        lines.append(f"__vector__ __global__ __aicore__ void {k.name}({params})")
        lines.append("{")
        lines.append("    asc_init();")
        lines.append("")
        for buf in k.buffers:
            c_type = _DTYPE_TO_C[buf.dtype.value]
            count = buf.stages * buf.elems
            lines.append(f"    __ubuf__ {c_type} {buf.name}[{count}];")
        lines.append("")
        if self.looped:
            for lo, hi, signature in self._regions():
                if hi - lo == self._unroll:
                    if lo == 0:
                        label = "prologue"
                    elif hi == self.tiles:
                        label = "epilogue"
                    else:
                        label = "peeled"
                    lines.append(f"    // {label} i = {lo}")
                    self._emit_group(lines, "    ", lo, signature)
                else:
                    lines.append(f"    for (uint32_t i = {lo}; i < {hi}; i += {self._unroll}) {{")
                    self._emit_group(lines, "        ", None, signature)
                    lines.append("    }")
        else:
            for j, stmt in enumerate(self.body):
                lines.extend("    " + line for line in self._emit_stmt(stmt, j, 0, None, (), set()))
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def _emit_group(self, lines, indent: str, i_value, signature) -> None:
        for sub in range(self._unroll):
            if self._unroll > 1:
                lines.append(f"{indent}// 槽位 {sub}")
            waited = set()
            for j, stmt in enumerate(self.body):
                lines.extend(indent + line for line in self._emit_stmt(stmt, j, sub, i_value, signature, waited))

    def _emit_stmt(self, stmt, j: int, k: int, i_value, signature, waited: set) -> list:
        if isinstance(stmt, CopyStmt):
            return self._emit_copy(stmt, j, k, i_value, signature, waited)
        if isinstance(stmt, ComputeStmt):
            return self._emit_compute(stmt, j, k, i_value, signature, waited)
        if isinstance(stmt, SyncStmt):
            return self._emit_sync(stmt)
        raise CodegenError(f"未知语句类型 {type(stmt).__name__}")

    def _war_wait(self, buf, k: int, signature, waited: set) -> list:
        if buf.name not in self._war or not self.looped or self.tiles <= buf.stages:
            return []
        if self._war_decision(signature, buf, k, "wait") != "emit":
            return []
        # 上一轮只 notify 一次。同一轮对同一槽位写多次时，只在第一次写入前 wait。
        key = (buf.name, k % buf.stages)
        if key in waited:
            return []
        waited.add(key)
        p, q = self._war[buf.name]
        return [f"asc_sync_wait({_PIPE_TO_C[q]}, {_PIPE_TO_C[p]}, {self._war_event_id(buf, p, q, k)});"]

    def _war_notify(self, buf, k: int, signature) -> list:
        if buf.name not in self._war or not self.looped or self.tiles <= buf.stages:
            return []
        if self._war_decision(signature, buf, k, "notify") != "emit":
            return []
        p, q = self._war[buf.name]
        return [f"asc_sync_notify({_PIPE_TO_C[q]}, {_PIPE_TO_C[p]}, {self._war_event_id(buf, p, q, k)});"]

    def _emit_copy(self, stmt: CopyStmt, j: int, k: int, i_value, signature, waited: set) -> list:
        if stmt.pipe == Pipe.MTE2 and isinstance(stmt.src, GmRef) and isinstance(stmt.dst, BufRef):
            buf = stmt.dst.buffer
            lines = self._war_wait(buf, k, signature, waited)
            lines.append(
                f"asc_copy_gm2ub({self._buf_ptr(stmt.dst, k)}, {self._gm_ptr(stmt.src, j, 0, k, i_value)}, 1, {_burst(buf)}, 0, 0);"
            )
            return lines
        if stmt.pipe == Pipe.MTE3 and isinstance(stmt.src, BufRef) and isinstance(stmt.dst, GmRef):
            buf = stmt.src.buffer
            lines = [
                f"asc_copy_ub2gm({self._gm_ptr(stmt.dst, j, 1, k, i_value)}, {self._buf_ptr(stmt.src, k)}, 1, {_burst(buf)}, 0, 0);"
            ]
            if self._last_read.get(buf.name) == j:
                lines.extend(self._war_notify(buf, k, signature))
            return lines
        raise CodegenError(f"v0.2 不支持的 copy 形态：pipe={stmt.pipe.value}")

    def _emit_compute(self, stmt: ComputeStmt, j: int, k: int, i_value, signature, waited: set) -> list:
        if stmt.op not in _SUPPORTED_COMPUTE:
            raise CodegenError(f"v0.2 代码生成只支持 {sorted(_SUPPORTED_COMPUTE)}，得到 {stmt.op!r}（trace/verify 可用）")
        dst = stmt.dst
        for src in stmt.srcs:
            if not isinstance(src, BufRef) or src.buffer.stage_bytes != dst.buffer.stage_bytes:
                raise CodegenError(
                    f"add 的源和目的单 stage 字节数必须相同（目的 {dst.buffer.name} 为 {dst.buffer.stage_bytes}B），"
                    "否则 repeat 会读过较短的 buffer"
                )
        if dst.buffer.stage_bytes % _REPEAT_BYTES != 0:
            raise CodegenError(
                f"buffer {dst.buffer.name} 单 stage {dst.buffer.stage_bytes}B 不是 {_REPEAT_BYTES}B 的整数倍，无法计算 repeat"
            )
        repeat = dst.buffer.stage_bytes // _REPEAT_BYTES
        if repeat > _REPEAT_MAX:
            raise CodegenError(
                f"buffer {dst.buffer.name} 单 stage 需要 repeat={repeat}，超过 asc_add 的 uint8_t 上限 {_REPEAT_MAX}；"
                "请减小 tile 或拆分计算"
            )
        lines = self._war_wait(dst.buffer, k, signature, waited)
        ptrs = [self._buf_ptr(dst, k)] + [self._buf_ptr(s, k) for s in stmt.srcs]
        lines.append(f"asc_add({ptrs[0]}, {ptrs[1]}, {ptrs[2]}, {repeat}, 1, 1, 1, 8, 8, 8);")
        released = set()
        for s in stmt.srcs:
            if s.buffer.name in released:
                continue  # 同一语句重复读同一 buffer，只释放一次
            released.add(s.buffer.name)
            if self._last_read.get(s.buffer.name) != j:
                continue  # 只在该槽位的最后一次消费之后释放（复审第 1 条）
            lines.extend(self._war_notify(s.buffer, k, signature))
        return lines

    def _emit_sync(self, stmt: SyncStmt) -> list:
        pair = (stmt.producer, stmt.consumer)
        base = self._alloc(pair, ("fwd", tuple(sorted(b.name for b in stmt.on))))
        ev = f"EVENT_ID{base}"
        p, q = _PIPE_TO_C[stmt.producer], _PIPE_TO_C[stmt.consumer]
        return [f"asc_sync_notify({p}, {q}, {ev});", f"asc_sync_wait({p}, {q}, {ev});"]


def _burst(buf) -> int:
    if buf.stage_bytes % _BLOCK_BYTES != 0:
        raise CodegenError(f"buffer {buf.name} 单 stage {buf.stage_bytes}B 不是 {_BLOCK_BYTES}B 的整数倍")
    return buf.stage_bytes // _BLOCK_BYTES


def _stmt_refs(stmt) -> list:
    if isinstance(stmt, CopyStmt):
        return [stmt.src, stmt.dst]
    if isinstance(stmt, ComputeStmt):
        return [stmt.dst] + list(stmt.srcs)
    return []


def _stmt_reads(stmt) -> list:
    if isinstance(stmt, CopyStmt):
        return [stmt.src] if isinstance(stmt.src, BufRef) else []
    if isinstance(stmt, ComputeStmt):
        return [s for s in stmt.srcs if isinstance(s, BufRef)]
    return []
