# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

"""代码生成：Kernel 模型 → 调用 C API 的 .asc 源码。

生成规则：
- 先跑检查器，存在 block 诊断即拒绝生成（fail closed）。
- event 分配（ADR 0010/0011）：event id 按 (生产PIPE, 消费PIPE) 对独立分配，且全部为
  字面量。循环按流水深度展开，同一 id 上 notify/wait 严格交替；TILES 不能被流水深度整除时拒绝生成。
- 软件流水（ADR 0013，M0 的去守卫通过线）：把循环切成 prologue / 稳态 / epilogue。
  稳态里的 WAR wait 与 notify 都是无条件指令，不再生成 `if (i >= N)`。
- WAR 释放边由 stages 推导：复用槽位前 wait（消费, 生产），**该槽位在循环体内的
  最后一次消费之后**才 notify（复审 2026-09-26 第 1 条）；同一语句重复读同一
  buffer 只释放一次。
- 计算 op 已在 CANN 9.1.0 的 3510 上核对：f32 add、f32 leakyrelu、f16→f32 cast、
  f32 repeat_reduce_sum。cast 用 `vlds(..., UNPK_B16)` 和 `asc_half2float(dst, src, mask)`，
  不用 asc-devkit 才有的 `asc_loadalign_unpack`。datablock_reduce_sum 仍拒绝生成。
  向量计算在 3510 上没有 UB 指针版实现，lowering 为 reg 向量风格（ADR 0014）。
  搬运 burst_len 在 3510 上单位为字节（2201 为 32B 块数），搬运量直接发单 stage 字节数。
- v0.2 不生成多核切分；不支持跨 PIPE 就地改写（一个 buffer 的生产 PIPE 必须唯一）。
"""

from __future__ import annotations

import math

from ..devices import load_device
from ..catalog import BINARY_I32, SCALAR_I32, lowering_kind, reg_c_dtype
from ..model.core import BufRef, DType, GmRef, Pipe, Space
from ..model.stmts import ComputeStmt, CopyStmt, SyncStmt
from ..verify import verify
from .reroll import reroll

_REPEAT_BYTES = 256  # VL=256B；b32 模式每个 VF 迭代处理 64 个 f32
_BLOCK_BYTES = 32
_BURST_LEN_MAX = 65535  # 3510 的 asc_copy_gm2ub/ub2gm burst_len 是 uint16_t（单位：字节）

_DTYPE_TO_C = {"u8": "uint8_t", "i32": "int32_t", "f16": "half", "f32": "float"}
_PIPE_TO_C = {
    Pipe.S: "PIPE_S",
    Pipe.V: "PIPE_V",
    Pipe.M: "PIPE_M",
    Pipe.MTE1: "PIPE_MTE1",
    Pipe.MTE2: "PIPE_MTE2",
    Pipe.MTE3: "PIPE_MTE3",
    Pipe.FIX: "PIPE_FIX",
}
_SPACE_QUAL = {
    Space.UB: "__ubuf__",
    Space.L1: "__cbuf__",
    Space.L0A: "__ca__",
    Space.L0B: "__cb__",
    Space.L0C: "__cc__",
}

_SUPPORTED_COMPUTE = {
    "add", "leakyrelu", "cast", "repeat_reduce_sum", "select",
    "select_gt", "select_gt_scalar", "select_lt", "select_lt_scalar",
    "select_ne", "select_ne_scalar", "select_eq", "select_eq_scalar",
    "select_ge", "select_ge_scalar", "select_le", "select_le_scalar",
    "duplicate", "arange", "mmad",
}

_LICENSE = """/* !
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This file is generated by ascendc-ir. DO NOT EDIT MANUALLY.
 * See LICENSE in the root of the software repository for the full text of the License.
 */"""

# ADR 0014：3510 上 add 的 reg 向量 lowering。写法逐行对齐官方样例
# asc-devkit examples/02_simd_c_api/00_introduction/04_reg_base_add_compute/c_api_simd_add。
# asc_update_mask_b32 的 value 是引用参数，每次调用自动减去 64（b32 的 VF 元素数），
# 尾块由掩码收敛；调用点传入的 data_len 是单 stage 元素数。
_ADD_VF_HELPER = """__simd_vf__ inline void add_vf(
    __ubuf__ float* x_local, __ubuf__ float* y_local, __ubuf__ float* z_local, uint32_t data_len)
{
    uint16_t one_rep_size = asc_get_vf_len() / sizeof(float);
    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;

    vector_bool vmask;
    vector_float reg_src0;
    vector_float reg_src1;
    vector_float reg_dst;
    for (uint16_t i = 0; i < repeat_time; ++i) {
        vmask = asc_update_mask_b32(data_len);
        asc_load(reg_src0, x_local + i * one_rep_size);
        asc_load(reg_src1, y_local + i * one_rep_size);
        asc_add(reg_dst, reg_src0, reg_src1, vmask);
        asc_store(z_local + i * one_rep_size, reg_dst);
    }
}"""

_LEAKYRELU_VF_HELPER = """__simd_vf__ inline void leakyrelu_vf(
    __ubuf__ float* x_local, __ubuf__ float* y_local, uint32_t data_len, float alpha)
{
    uint16_t one_rep_size = asc_get_vf_len() / sizeof(float);
    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;

    vector_bool vmask;
    vector_float reg_src;
    vector_float reg_dst;
    for (uint16_t i = 0; i < repeat_time; ++i) {
        vmask = asc_update_mask_b32(data_len);
        asc_load(reg_src, x_local + i * one_rep_size);
        asc_leakyrelu(reg_dst, reg_src, alpha, vmask);
        asc_store(y_local + i * one_rep_size, reg_dst);
    }
}"""

_CAST_VF_HELPER = """__simd_vf__ inline void cast_half_to_float_vf(
    __ubuf__ half* x_local, __ubuf__ float* y_local, uint32_t data_len)
{
    uint16_t one_rep_size = asc_get_vf_len() / sizeof(float);
    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;

    vector_bool vmask;
    vector_half reg_src;
    vector_float reg_dst;
    for (uint16_t i = 0; i < repeat_time; ++i) {
        vmask = asc_update_mask_b32(data_len);
        vlds(reg_src, x_local + i * one_rep_size, 0, UNPK_B16);
        asc_half2float(reg_dst, reg_src, vmask);
        asc_storealign(y_local + i * one_rep_size, reg_dst, vmask);
    }
}"""

_REDUCE_VF_HELPER = """__simd_vf__ inline void reduce_sum_vf(
    __ubuf__ float* x_local, __ubuf__ float* y_local, uint32_t data_len)
{
    uint16_t one_rep_size = asc_get_vf_len() / sizeof(float);
    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;

    vector_bool vmask;
    vector_float src_reg;
    vector_float dst_reg;
    vector_float acc_reg;
    asc_duplicate_scalar(acc_reg, 0.0f);
    for (uint16_t i = 0; i < repeat_time; ++i) {
        vmask = asc_update_mask_b32(data_len);
        asc_loadalign(src_reg, x_local + i * one_rep_size);
        asc_reduce_sum(dst_reg, src_reg, vmask);
        asc_add(acc_reg, acc_reg, dst_reg, vmask);
    }
    asc_storealign(y_local, acc_reg, vmask);
}"""

_SELECT_VF_HELPER = """__simd_vf__ inline void select_vf(
    __ubuf__ float* src0, __ubuf__ float* src1, __ubuf__ uint32_t* mask_local, __ubuf__ float* dst,
    uint32_t data_len)
{
    uint16_t one_rep_size = asc_get_vf_len() / sizeof(float);
    uint16_t mask_rep_size = asc_get_vf_len() / 8;
    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;

    vector_bool vmask;
    vector_float reg_src0;
    vector_float reg_src1;
    vector_float reg_dst;
    vector_bool store_mask = asc_create_mask_b32(PAT_ALL);
    for (uint16_t i = 0; i < repeat_time; ++i) {
        asc_loadalign(reg_src0, src0 + i * one_rep_size);
        asc_loadalign(reg_src1, src1 + i * one_rep_size);
        asc_loadalign_postupdate(vmask, mask_local, mask_rep_size);
        asc_select(reg_dst, reg_src0, reg_src1, vmask);
        asc_storealign(dst + i * one_rep_size, reg_dst, store_mask);
    }
}"""

def _compare_select_helper(name: str, compare: str, scalar: bool) -> str:
    value = ", float value" if scalar else ""
    cmp_args = "reg_src0, value, vmask" if scalar else "reg_src0, reg_src1, vmask"
    return (
        f"__simd_vf__ inline void {name}_vf(\n"
        f"    __ubuf__ float* src0, __ubuf__ float* src1, __ubuf__ float* dst, uint32_t data_len{value})\n"
        "{\n"
        "    uint16_t one_rep_size = asc_get_vf_len() / sizeof(float);\n"
        "    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;\n"
        "\n"
        "    vector_bool vmask;\n"
        "    vector_bool cmp_mask;\n"
        "    vector_float reg_src0;\n"
        "    vector_float reg_src1;\n"
        "    vector_float reg_dst;\n"
        "    for (uint16_t i = 0; i < repeat_time; ++i) {\n"
        "        vmask = asc_update_mask_b32(data_len);\n"
        "        asc_loadalign(reg_src0, src0 + i * one_rep_size);\n"
        "        asc_loadalign(reg_src1, src1 + i * one_rep_size);\n"
        f"        {compare}(cmp_mask, {cmp_args});\n"
        "        asc_select(reg_dst, reg_src0, reg_src1, cmp_mask);\n"
        "        asc_storealign(dst + i * one_rep_size, reg_dst, vmask);\n"
        "    }\n"
        "}"
    )


_SELECT_GT_VF_HELPER = _compare_select_helper("select_gt", "asc_gt", scalar=False)
_SELECT_GT_SCALAR_VF_HELPER = _compare_select_helper("select_gt_scalar", "asc_gt_scalar", scalar=True)
_SELECT_LT_VF_HELPER = _compare_select_helper("select_lt", "asc_lt", scalar=False)
_SELECT_LT_SCALAR_VF_HELPER = _compare_select_helper("select_lt_scalar", "asc_lt_scalar", scalar=True)
_SELECT_NE_VF_HELPER = _compare_select_helper("select_ne", "asc_ne", scalar=False)
_SELECT_NE_SCALAR_VF_HELPER = _compare_select_helper("select_ne_scalar", "asc_ne_scalar", scalar=True)
_SELECT_EQ_VF_HELPER = _compare_select_helper("select_eq", "asc_eq", scalar=False)
_SELECT_EQ_SCALAR_VF_HELPER = _compare_select_helper("select_eq_scalar", "asc_eq_scalar", scalar=True)
_SELECT_GE_VF_HELPER = _compare_select_helper("select_ge", "asc_ge", scalar=False)
_SELECT_GE_SCALAR_VF_HELPER = _compare_select_helper("select_ge_scalar", "asc_ge_scalar", scalar=True)
_SELECT_LE_VF_HELPER = _compare_select_helper("select_le", "asc_le", scalar=False)
_SELECT_LE_SCALAR_VF_HELPER = _compare_select_helper("select_le_scalar", "asc_le_scalar", scalar=True)

_DUPLICATE_VF_HELPER = """__simd_vf__ inline void duplicate_vf(
    __ubuf__ float* dst, uint32_t data_len, float value)
{
    uint16_t one_rep_size = asc_get_vf_len() / sizeof(float);
    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;

    vector_bool vmask;
    vector_float reg_dst;
    for (uint16_t i = 0; i < repeat_time; ++i) {
        vmask = asc_update_mask_b32(data_len);
        asc_duplicate_scalar(reg_dst, value, vmask);
        asc_storealign(dst + i * one_rep_size, reg_dst, vmask);
    }
}"""

_ARANGE_VF_HELPER = """__simd_vf__ inline void arange_vf(
    __ubuf__ float* dst, uint32_t data_len, float start_value)
{
    uint16_t one_rep_size = asc_get_vf_len() / sizeof(float);
    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;

    vector_bool vmask = asc_create_mask_b32(PAT_ALL);
    vector_float reg_dst;
    for (uint16_t i = 0; i < repeat_time; ++i) {
        asc_arange(reg_dst, start_value);
        asc_storealign(dst + i * one_rep_size, reg_dst, vmask);
        start_value += static_cast<float>(one_rep_size);
    }
}"""

_HELPERS = {
    "add": _ADD_VF_HELPER,
    "leakyrelu": _LEAKYRELU_VF_HELPER,
    "cast": _CAST_VF_HELPER,
    "repeat_reduce_sum": _REDUCE_VF_HELPER,
    "select": _SELECT_VF_HELPER,
    "select_gt": _SELECT_GT_VF_HELPER,
    "select_gt_scalar": _SELECT_GT_SCALAR_VF_HELPER,
    "select_lt": _SELECT_LT_VF_HELPER,
    "select_lt_scalar": _SELECT_LT_SCALAR_VF_HELPER,
    "select_ne": _SELECT_NE_VF_HELPER,
    "select_ne_scalar": _SELECT_NE_SCALAR_VF_HELPER,
    "select_eq": _SELECT_EQ_VF_HELPER,
    "select_eq_scalar": _SELECT_EQ_SCALAR_VF_HELPER,
    "select_ge": _SELECT_GE_VF_HELPER,
    "select_ge_scalar": _SELECT_GE_SCALAR_VF_HELPER,
    "select_le": _SELECT_LE_VF_HELPER,
    "select_le_scalar": _SELECT_LE_SCALAR_VF_HELPER,
    "duplicate": _DUPLICATE_VF_HELPER,
    "arange": _ARANGE_VF_HELPER,
}


class CodegenError(Exception):
    pass


def generate(kernel, device=None) -> str:
    dev = device if device is not None else load_device(kernel.device)
    blocks = [d for d in verify(kernel, dev) if d.severity == "block"]
    if blocks:
        detail = "; ".join(f"{d.id}@{d.callsite.line}: {d.message}" for d in blocks)
        raise CodegenError(f"检查器拒绝生成：{detail}")
    tiles, body, epilogue, ok, mmad_init_first = reroll(kernel)
    if not ok:
        raise CodegenError(
            f"循环重卷失败：trace 展开的 {len(kernel.statements)} 条语句不满足仿射规律，"
            "或存在无循环标记的槽位复用。循环体内的 sync 必须写 stage=迭代号；"
            "循环体语句保持一致、GM 偏移关于 i 仿射、buffer 槽位为 i % stages"
        )
    return _Emitter(kernel, dev, tiles, body, epilogue, mmad_init_first).emit()


class _Emitter:
    def __init__(self, kernel, device, tiles, body, epilogue, mmad_init_first):
        self.kernel = kernel
        self.device = device
        self.tiles = tiles
        self.body = body
        self.epilogue = epilogue
        self.mmad_init_first = mmad_init_first
        self.looped = tiles > 1
        self._slot_from_ref = False
        self.per = len(body) if tiles > 1 else len(kernel.statements)
        self._pair_events = {}  # (set_pipe, wait_pipe) -> {channel_key: base_id}
        self._pair_used = {}  # (set_pipe, wait_pipe) -> int
        self._war = self._analyze_war()
        self._last_read = self._analyze_last_reads()
        self._unroll = self._unroll_factor()

    # ---- 分析 ----

    def _analyze_war(self):
        """每 buffer 的生产/消费 PIPE；跨 PIPE 的 buffer 需要 WAR 通道。"""
        war = {}
        scope = self.body if self.looped else self.kernel.statements
        for buf in self.kernel.buffers:
            writers, readers = set(), set()
            for stmt in scope:
                if isinstance(stmt, CopyStmt):
                    if isinstance(stmt.dst, BufRef) and stmt.dst.buffer is buf:
                        writers.add(stmt.pipe)
                    if isinstance(stmt.src, BufRef) and stmt.src.buffer is buf:
                        readers.add(stmt.pipe)
                elif isinstance(stmt, ComputeStmt):
                    if isinstance(stmt.dst, BufRef) and stmt.dst.buffer is buf:
                        writers.add(stmt.pipe)
                    for s in stmt.srcs:
                        if isinstance(s, BufRef) and s.buffer is buf:
                            readers.add(stmt.pipe)
            cross = readers - writers
            if len(writers) == 1 and len(cross) == 1:
                p, q = next(iter(writers)), next(iter(cross))
                if p != q:
                    war[buf.name] = (p, q)
            elif len(writers) == 1 and not cross:
                continue
            elif writers or readers:
                raise CodegenError(
                    f"buffer {buf.name} 有多个生产/消费 PIPE（{sorted(p.value for p in writers)} / "
                    f"{sorted(p.value for p in readers)}），v0.2 不支持跨 PIPE 就地改写；"
                    "请读旧 buffer、写新 buffer"
                )
        return war

    def _analyze_last_reads(self):
        """每个 buffer 在循环体内最后一次被读的语句下标（WAR 释放点，复审第 1 条）。"""
        last = {}
        for j, stmt in enumerate(self.body):
            for ref in _stmt_reads(stmt):
                last[ref.buffer.name] = j
        return last

    def _unroll_factor(self) -> int:
        """循环按各 buffer 流水深度的最小公倍数展开；TILES 须被整除。"""
        if not self.looped:
            return 1
        factor = 1
        for buf in self.kernel.buffers:
            factor = math.lcm(factor, buf.stages)
        if self.tiles % factor != 0:
            raise CodegenError(
                f"循环轮数 {self.tiles} 不能被流水深度 {factor} 整除，无法按槽位展开；"
                "请调整 TILES 或 stages"
            )
        return factor

    # ---- event 分配（按 PIPE 对独立，全部字面量）----

    def _alloc(self, pair, key, n: int = 1) -> int:
        channels = self._pair_events.setdefault(pair, {})
        if key in channels:
            return channels[key]
        used = self._pair_used.get(pair, 0)
        if used + n > self.device.event_ids:
            raise CodegenError(
                f"PIPE 对 {pair[0].value}→{pair[1].value} 上 event 通道需要 {used + n} 个 id，"
                f"超过每对 PIPE 的 event_ids={self.device.event_ids}"
            )
        channels[key] = used
        self._pair_used[pair] = used + n
        return used

    def _war_event_id(self, buf, producer: Pipe, consumer: Pipe, k: int) -> str:
        """WAR 通道按槽位一个字面量 id，保证同一 id 上 notify/wait 严格交替。"""
        base = self._alloc((consumer, producer), ("war", buf.name), buf.stages)
        return f"EVENT_ID{base + k % buf.stages}"

    # ---- 引用表达式（k 为展开后的子迭代号，槽位与偏移均为字面量/仿射式）----

    def _buf_ptr(self, ref: BufRef, k: int) -> str:
        buf = ref.buffer
        if buf.stages == 1:
            return buf.name
        # 直写形态和循环收尾每条语句自带槽位。循环体的槽位由展开下标 k 决定。
        slot = ref.stage if self._slot_from_ref or not self.looped else k % buf.stages
        return buf.name if slot == 0 else f"{buf.name} + {slot * buf.elems}"

    def _gm_ptr(self, ref: GmRef, stmt_index: int, ref_index: int, k: int, i_value) -> str:
        base = ref.offset  # body 是第 0 轮，offset 即基址。收尾不在循环里，用它自己的偏移。
        if not self.looped or self._slot_from_ref:
            return ref.param.name if base == 0 else f"{ref.param.name} + {base}"
        stride = self._gm_stride(stmt_index, ref_index)
        if i_value is not None:
            offset = base + (i_value + k) * stride
            return ref.param.name if offset == 0 else f"{ref.param.name} + {offset}"
        if stride == 0:
            return ref.param.name if base == 0 else f"{ref.param.name} + {base}"
        term = f"i * {stride}" if k == 0 else f"(i + {k}) * {stride}"
        if base == 0:
            return f"{ref.param.name} + {term}"
        return f"{ref.param.name} + {base} + {term}"

    def _gm_stride(self, stmt_index: int, ref_index: int) -> int:
        first = _stmt_refs(self.kernel.statements[stmt_index])[ref_index]
        second = _stmt_refs(self.kernel.statements[self.per + stmt_index])[ref_index]
        return second.offset - first.offset

    # ---- 软件流水：同一段里 WAR 的有无必须对每个 i 都一样，才能不写 if ----

    def _signature(self, group_start: int) -> tuple:
        items = []
        for buf in self.kernel.buffers:
            if buf.name not in self._war or self.tiles <= buf.stages:
                continue
            for k in range(self._unroll):
                gi = group_start + k
                wait = "emit" if gi >= buf.stages else "omit"
                notify = "emit" if gi + buf.stages < self.tiles else "omit"
                items.append((buf.name, k, wait, notify))
        return tuple(items)

    def _regions(self) -> list:
        starts = list(range(0, self.tiles, self._unroll))
        regions = []
        index = 0
        while index < len(starts):
            signature = self._signature(starts[index])
            end = index + 1
            while end < len(starts) and self._signature(starts[end]) == signature:
                end += 1
            lo = starts[index]
            hi = starts[end - 1] + self._unroll
            regions.append((lo, hi, signature))
            index = end
        return regions

    def _emit_regions(self) -> list:
        """第一轮 mmad 负责清零时，把它从后续累加循环里剥出来，稳态里就不必再写 if。"""
        regions = self._regions()
        if not self.mmad_init_first:
            return regions
        peeled = []
        for lo, hi, signature in regions:
            if lo == 0 and hi - lo > self._unroll:
                peeled.append((0, self._unroll, signature))
                peeled.append((self._unroll, hi, signature))
            else:
                peeled.append((lo, hi, signature))
        return peeled

    def _war_decision(self, signature, buf, k: int, which: str) -> str:
        for name, slot, wait, notify in signature:
            if name == buf.name and slot == k:
                return wait if which == "wait" else notify
        return "omit"

    # ---- 发射 ----

    def emit(self) -> str:
        k = self.kernel
        lines = [_LICENSE, "", '#include "c_api/asc_simd.h"', ""]
        ops = {stmt.op for stmt in k.statements if isinstance(stmt, ComputeStmt)}
        for op in (
            "add",
            "leakyrelu",
            "cast",
            "repeat_reduce_sum",
            "select",
            "select_gt",
            "select_gt_scalar",
            "select_lt",
            "select_lt_scalar",
            "select_ne",
            "select_ne_scalar",
            "select_eq",
            "select_eq_scalar",
            "select_ge",
            "select_ge_scalar",
            "select_le",
            "select_le_scalar",
            "duplicate",
            "arange",
        ):
            if op in ops:
                lines.extend(_HELPERS[op].splitlines())
                lines.append("")
        emitted = set()
        for op in sorted(ops):
            kind = lowering_kind(op)
            if kind not in {"reg_binary", "reg_unary", "reg_scalar"} or op in emitted:
                continue
            emitted.add(op)
            lines.extend(_reg_helper(op, kind, reg_c_dtype(op) or "f32").splitlines())
            lines.append("")
        params = ", ".join(f"__gm__ {_DTYPE_TO_C[p.dtype.value]}* {p.name}" for p in k.params)
        cube = any(buf.space is not Space.UB for buf in k.buffers)
        if cube and any(buf.space is Space.UB for buf in k.buffers):
            raise CodegenError("这一批不能在同一个核里同时放 UB 向量缓冲和 Cube 缓冲")
        prefix = "__global__ __cube__" if cube else "__vector__ __global__ __aicore__"
        lines.append(f"{prefix} void {k.name}({params})")
        lines.append("{")
        lines.append("    asc_init();")
        lines.append("")
        for buf in k.buffers:
            c_type = _DTYPE_TO_C[buf.dtype.value]
            count = buf.stages * buf.elems
            lines.append(f"    {_SPACE_QUAL[buf.space]} {c_type} {buf.name}[{count}];")
        lines.append("")
        if self.looped:
            for lo, hi, signature in self._emit_regions():
                if hi - lo == self._unroll:
                    if lo == 0:
                        label = "prologue"
                    elif hi == self.tiles and not self.epilogue:
                        label = "epilogue"
                    else:
                        label = "peeled"
                    lines.append(f"    // {label} i = {lo}")
                    self._emit_group(lines, "    ", lo, signature)
                else:
                    lines.append(f"    for (uint32_t i = {lo}; i < {hi}; i += {self._unroll}) {{")
                    self._emit_group(lines, "        ", None, signature)
                    lines.append("    }")
            if self.epilogue:
                lines.append("    // 循环之后")
                self._slot_from_ref = True
                try:
                    for j, stmt in enumerate(self.epilogue):
                        lines.extend("    " + line for line in self._emit_stmt(stmt, j, 0, None, (), set()))
                finally:
                    self._slot_from_ref = False
        else:
            for j, stmt in enumerate(self.body):
                lines.extend("    " + line for line in self._emit_stmt(stmt, j, 0, None, (), set()))
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def _emit_group(self, lines, indent: str, i_value, signature) -> None:
        for sub in range(self._unroll):
            if self._unroll > 1:
                lines.append(f"{indent}// 槽位 {sub}")
            waited = set()
            for j, stmt in enumerate(self.body):
                lines.extend(indent + line for line in self._emit_stmt(stmt, j, sub, i_value, signature, waited))

    def _emit_stmt(self, stmt, j: int, k: int, i_value, signature, waited: set) -> list:
        if isinstance(stmt, CopyStmt):
            return self._emit_copy(stmt, j, k, i_value, signature, waited)
        if isinstance(stmt, ComputeStmt):
            return self._emit_compute(stmt, j, k, i_value, signature, waited)
        if isinstance(stmt, SyncStmt):
            return self._emit_sync(stmt)
        raise CodegenError(f"未知语句类型 {type(stmt).__name__}")

    def _war_wait(self, buf, k: int, signature, waited: set) -> list:
        if buf.name not in self._war or not self.looped or self.tiles <= buf.stages:
            return []
        if self._war_decision(signature, buf, k, "wait") != "emit":
            return []
        # 上一轮只 notify 一次。同一轮对同一槽位写多次时，只在第一次写入前 wait。
        key = (buf.name, k % buf.stages)
        if key in waited:
            return []
        waited.add(key)
        p, q = self._war[buf.name]
        return [f"asc_sync_wait({_PIPE_TO_C[q]}, {_PIPE_TO_C[p]}, {self._war_event_id(buf, p, q, k)});"]

    def _war_notify(self, buf, k: int, signature) -> list:
        if buf.name not in self._war or not self.looped or self.tiles <= buf.stages:
            return []
        if self._war_decision(signature, buf, k, "notify") != "emit":
            return []
        p, q = self._war[buf.name]
        return [f"asc_sync_notify({_PIPE_TO_C[q]}, {_PIPE_TO_C[p]}, {self._war_event_id(buf, p, q, k)});"]

    def _emit_copy(self, stmt: CopyStmt, j: int, k: int, i_value, signature, waited: set) -> list:
        if stmt.form != "linear":
            return self._emit_cube_copy(stmt, j, k, i_value, signature, waited)
        if stmt.pipe == Pipe.MTE2 and isinstance(stmt.src, GmRef) and isinstance(stmt.dst, BufRef):
            if stmt.dst.buffer.space is not Space.UB:
                raise CodegenError(f"linear 搬运的目的 {stmt.dst.buffer.name} 不在 ubuf")
            buf = stmt.dst.buffer
            lines = self._war_wait(buf, k, signature, waited)
            lines.append(
                f"asc_copy_gm2ub({self._buf_ptr(stmt.dst, k)}, {self._gm_ptr(stmt.src, j, 0, k, i_value)}, 1, {_burst(buf)}, 0, 0);"
            )
            return lines
        if stmt.pipe == Pipe.MTE3 and isinstance(stmt.src, BufRef) and isinstance(stmt.dst, GmRef):
            buf = stmt.src.buffer
            lines = [
                f"asc_copy_ub2gm({self._gm_ptr(stmt.dst, j, 1, k, i_value)}, {self._buf_ptr(stmt.src, k)}, 1, {_burst(buf)}, 0, 0);"
            ]
            if self._last_read.get(buf.name) == j:
                lines.extend(self._war_notify(buf, k, signature))
            return lines
        raise CodegenError(f"v0.2 不支持的 copy 形态：pipe={stmt.pipe.value}")

    def _emit_compute(self, stmt: ComputeStmt, j: int, k: int, i_value, signature, waited: set) -> list:
        if stmt.op == "add":
            return self._emit_add(stmt, j, k, signature, waited)
        if stmt.op == "leakyrelu":
            return self._emit_leakyrelu(stmt, j, k, signature, waited)
        if stmt.op == "cast":
            return self._emit_cast(stmt, j, k, signature, waited)
        if stmt.op == "repeat_reduce_sum":
            return self._emit_reduce(stmt, j, k, signature, waited)
        if stmt.op == "select":
            return self._emit_select(stmt, j, k, signature, waited)
        if stmt.op in {"select_gt", "select_lt", "select_ne", "select_eq", "select_ge", "select_le"}:
            return self._emit_select_gt(stmt, j, k, signature, waited)
        if stmt.op in {
            "select_gt_scalar", "select_lt_scalar", "select_ne_scalar",
            "select_eq_scalar", "select_ge_scalar", "select_le_scalar",
        }:
            return self._emit_select_gt_scalar(stmt, j, k, signature, waited)
        if stmt.op == "duplicate":
            return self._emit_duplicate(stmt, j, k, signature, waited)
        if stmt.op == "arange":
            return self._emit_arange(stmt, j, k, signature, waited)
        if stmt.op == "mmad":
            return self._emit_mmad(stmt, j, k, i_value, signature)
        kind = lowering_kind(stmt.op)
        if kind == "reg_binary":
            return self._emit_reg_binary(stmt, j, k, signature, waited)
        if kind == "reg_unary":
            return self._emit_reg_unary(stmt, j, k, signature, waited)
        if kind == "reg_scalar":
            return self._emit_reg_scalar(stmt, j, k, signature, waited)
        raise CodegenError(
            f"v0.2 代码生成只支持 {sorted(_SUPPORTED_COMPUTE)}，得到 {stmt.op!r}（trace/verify 可用）"
        )

    def _emit_cube_copy(self, stmt: CopyStmt, j: int, k: int, i_value, signature, waited: set) -> list:
        rows, cols = (int(stmt.scalars[0]), int(stmt.scalars[1]))
        row_stride = int(stmt.scalars[2]) if len(stmt.scalars) > 2 else cols
        if stmt.form in {"nd2nz", "dn2nz", "l12l0a", "l12l0b"} and stmt.dst.buffer.dtype is not DType.f16:
            raise CodegenError(f"{stmt.form} 这一批只生成 f16；f32 的 K 方向粒度不同，不能套用")
        if stmt.form == "nd2nz":
            # CANN 9.1.0 的 10 参形式：行距单位是元素，目的步长写在参数里。
            lines = self._war_wait(stmt.dst.buffer, k, signature, waited)
            dst = self._buf_ptr(stmt.dst, k)
            src = self._gm_ptr(stmt.src, j, 0, k, i_value)
            c0 = (rows + 15) // 16 * 16
            if not 1 <= row_stride <= 65535 or not 1 <= c0 <= 16384:
                raise CodegenError(f"nd2nz 的行距 {row_stride} 或 c0 步长 {c0} 超出 uint16")
            lines.append(
                f"asc_copy_gm2l1_nd2nz({dst}, {src}, 1, {rows}, {cols}, 0, {row_stride}, {c0}, 1, 0);"
            )
            return lines
        if stmt.form == "dn2nz":
            # 没有 10 参形式。9.1.0 的 L2 模式是 uint8，1 表示 NORMAL。
            lines = self._war_wait(stmt.dst.buffer, k, signature, waited)
            dst = self._buf_ptr(stmt.dst, k)
            src = self._gm_ptr(stmt.src, j, 0, k, i_value)
            aligned = (rows + 15) // 16 * 16
            config = (aligned << 32) | (1 << 16) | 1
            stride = row_stride * stmt.dst.buffer.dtype.nbytes
            lines.extend(
                [
                    f"asc_set_gm2l1_nz_para({config}ULL);",
                    "asc_copy_gm2l1_dn2nz("
                    f"{dst}, {src}, {stride}ULL, 1, {rows}, {cols}, 0, false);",
                ]
            )
            return lines
        if stmt.form in {"l12l0a", "l12l0b"}:
            m_step = (rows + 15) // 16
            k_step = (cols + 15) // 16
            if m_step > 255 or k_step > 255:
                raise CodegenError(f"{stmt.form} 的 step 超过 uint8：m_step={m_step} k_step={k_step}")
            fn = "asc_copy_l12l0a" if stmt.form == "l12l0a" else "asc_copy_l12l0b"
            lines = self._war_wait(stmt.dst.buffer, k, signature, waited)
            lines.append(
                f"{fn}({self._buf_ptr(stmt.dst, k)}, {self._buf_ptr(stmt.src, k)}, "
                f"0, 0, {m_step}, {k_step}, {m_step}, {m_step});"
            )
            if isinstance(stmt.src, BufRef) and self._last_read.get(stmt.src.buffer.name) == j:
                lines.extend(self._war_notify(stmt.src.buffer, k, signature))
            return lines
        if stmt.form == "l0c2gm":
            src_stride = (rows + 15) // 16 * 16
            return [
                "asc_set_l0c2gm_nz2nd(1, 0, 0);",
                "asc_copy_l0c2gm("
                f"{self._gm_ptr(stmt.dst, j, 1, k, i_value)}, {self._buf_ptr(stmt.src, k)}, "
                f"{cols}, {rows}, {cols}, {src_stride}, 0, 0, 0, false, true);",
            ]
        raise CodegenError(f"没有 {stmt.form} 的降级")

    def _emit_mmad(self, stmt: ComputeStmt, j: int, k: int, i_value, signature) -> list:
        m_dim, k_dim, n_dim, init = (int(x) for x in stmt.scalars)
        if self.mmad_init_first and self.looped:
            clears = i_value == 0 and k == 0
        else:
            clears = bool(init)
        init_c = "true" if clears else "false"
        lines = []
        if not clears:
            lines.append("asc_sync_pipe(PIPE_M);")
        lines.append(
            "asc_mmad("
            f"{self._buf_ptr(stmt.dst, k)}, {self._buf_ptr(stmt.srcs[0], k)}, {self._buf_ptr(stmt.srcs[1], k)}, "
            f"{m_dim}, {k_dim}, {n_dim}, 0, true, false, {init_c});"
        )
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _emit_reg_binary(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        dst = stmt.dst
        want = DType.i32 if stmt.op in BINARY_I32 else DType.f32
        self._require_ub(dst, stmt.op, want)
        for src in stmt.srcs:
            self._require_ub(src, stmt.op, want)
            if src.buffer.elems != dst.buffer.elems:
                raise CodegenError(f"{stmt.op} 的源和目的元素个数必须相同")
        self._require_vl(dst)
        lines = self._war_wait(dst.buffer, k, signature, waited)
        lines.append(
            f"{stmt.op}_vf({self._buf_ptr(stmt.srcs[0], k)}, {self._buf_ptr(stmt.srcs[1], k)}, "
            f"{self._buf_ptr(dst, k)}, {dst.buffer.elems});"
        )
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _emit_reg_unary(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        dst = stmt.dst
        src = stmt.srcs[0]
        self._require_f32_ub(dst, stmt.op)
        self._require_f32_ub(src, stmt.op)
        if src.buffer.elems != dst.buffer.elems:
            raise CodegenError(f"{stmt.op} 的源和目的元素个数必须相同")
        self._require_vl(dst)
        lines = self._war_wait(dst.buffer, k, signature, waited)
        lines.append(
            f"{stmt.op}_vf({self._buf_ptr(src, k)}, {self._buf_ptr(dst, k)}, {dst.buffer.elems});"
        )
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _emit_reg_scalar(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        dst = stmt.dst
        src = stmt.srcs[0]
        integer = stmt.op in SCALAR_I32
        want = DType.i32 if integer else DType.f32
        self._require_ub(dst, stmt.op, want)
        self._require_ub(src, stmt.op, want)
        if src.buffer.elems != dst.buffer.elems:
            raise CodegenError(f"{stmt.op} 的源和目的元素个数必须相同")
        self._require_vl(dst)
        if integer:
            literal = str(int(stmt.scalars[0]))
        else:
            literal = _f32_literal(stmt.scalars[0])
        lines = self._war_wait(dst.buffer, k, signature, waited)
        lines.append(
            f"{stmt.op}_vf({self._buf_ptr(src, k)}, {self._buf_ptr(dst, k)}, {dst.buffer.elems}, {literal});"
        )
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines


    def _emit_select(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        # 对照 select.asc：mask 在 UB 按 packed bits，字节数 = f32 个数 * 4 / 8。
        if len(stmt.srcs) != 3:
            raise CodegenError("select 需要三个源：src0、src1 和 packed mask 缓冲")
        dst = stmt.dst
        src0, src1, mask = stmt.srcs
        self._require_f32_ub(dst, stmt.op)
        self._require_f32_ub(src0, stmt.op)
        self._require_f32_ub(src1, stmt.op)
        if not isinstance(mask, BufRef) or mask.buffer.space is not Space.UB or mask.buffer.dtype is not DType.u8:
            raise CodegenError("select 的 mask 必须是 ubuf 上的 u8 packed bits")
        if src0.buffer.elems != dst.buffer.elems or src1.buffer.elems != dst.buffer.elems:
            raise CodegenError("select 的浮点源和目的元素个数必须相同")
        if dst.buffer.elems % 2 != 0:
            raise CodegenError("select 的 f32 元素个数必须为偶数，才能对齐 packed mask 字节数")
        expected_mask = dst.buffer.elems * dst.buffer.dtype.nbytes // 8
        if mask.buffer.elems != expected_mask:
            raise CodegenError(
                f"select 的 mask 需要 {expected_mask} 个 u8（= f32 个数 * 4 / 8），得到 {mask.buffer.elems}"
            )
        self._require_vl(dst)
        lines = self._war_wait(dst.buffer, k, signature, waited)
        lines.append(
            f"select_vf({self._buf_ptr(src0, k)}, {self._buf_ptr(src1, k)}, "
            f"(__ubuf__ uint32_t*){self._buf_ptr(mask, k)}, {self._buf_ptr(dst, k)}, {dst.buffer.elems});"
        )
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _emit_select_gt(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        if len(stmt.srcs) != 2:
            raise CodegenError("select_gt 需要两个浮点源")
        dst = stmt.dst
        src0, src1 = stmt.srcs
        self._require_f32_ub(dst, stmt.op)
        self._require_f32_ub(src0, stmt.op)
        self._require_f32_ub(src1, stmt.op)
        if src0.buffer.elems != dst.buffer.elems or src1.buffer.elems != dst.buffer.elems:
            raise CodegenError("select_gt 的源和目的元素个数必须相同")
        self._require_vl(dst)
        lines = self._war_wait(dst.buffer, k, signature, waited)
        lines.append(
            f"{stmt.op}_vf({self._buf_ptr(src0, k)}, {self._buf_ptr(src1, k)}, "
            f"{self._buf_ptr(dst, k)}, {dst.buffer.elems});"
        )
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _emit_select_gt_scalar(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        if len(stmt.srcs) != 2 or not stmt.scalars:
            raise CodegenError("select_gt_scalar 需要两个浮点源和一个标量")
        dst = stmt.dst
        src0, src1 = stmt.srcs
        self._require_f32_ub(dst, stmt.op)
        self._require_f32_ub(src0, stmt.op)
        self._require_f32_ub(src1, stmt.op)
        if src0.buffer.elems != dst.buffer.elems or src1.buffer.elems != dst.buffer.elems:
            raise CodegenError("select_gt_scalar 的源和目的元素个数必须相同")
        self._require_vl(dst)
        value = float(stmt.scalars[0])
        lines = self._war_wait(dst.buffer, k, signature, waited)
        lines.append(
            f"{stmt.op}_vf({self._buf_ptr(src0, k)}, {self._buf_ptr(src1, k)}, "
            f"{self._buf_ptr(dst, k)}, {dst.buffer.elems}, {_f32_literal(value)});"
        )
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _emit_duplicate(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        if stmt.srcs:
            raise CodegenError("duplicate 没有源向量，只有目的和标量")
        if not stmt.scalars:
            raise CodegenError("duplicate 需要一个标量")
        dst = stmt.dst
        self._require_f32_ub(dst, stmt.op)
        self._require_vl(dst)
        value = float(stmt.scalars[0])
        lines = self._war_wait(dst.buffer, k, signature, waited)
        lines.append(f"duplicate_vf({self._buf_ptr(dst, k)}, {dst.buffer.elems}, {_f32_literal(value)});")
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _emit_arange(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        # 对照 arange.asc：无源；asc_arange + PAT_ALL store；每 VL 块递增 start。
        if stmt.srcs:
            raise CodegenError("arange 没有源向量，只有目的和起始标量")
        if not stmt.scalars:
            raise CodegenError("arange 需要起始标量")
        dst = stmt.dst
        self._require_f32_ub(dst, stmt.op)
        self._require_vl(dst)
        start = float(stmt.scalars[0])
        lines = self._war_wait(dst.buffer, k, signature, waited)
        lines.append(f"arange_vf({self._buf_ptr(dst, k)}, {dst.buffer.elems}, {_f32_literal(start)});")
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _require_f32_ub(self, ref: BufRef, op: str) -> None:
        self._require_ub(ref, op, DType.f32)

    def _require_ub(self, ref: BufRef, op: str, dtype: DType) -> None:
        if not isinstance(ref, BufRef) or ref.buffer.dtype is not dtype or ref.buffer.space is not Space.UB:
            raise CodegenError(f"{op} 这一批只生成 ubuf 上的 {dtype.value}")

    def _emit_add(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        dst = stmt.dst
        for src in stmt.srcs:
            if not isinstance(src, BufRef) or src.buffer.stage_bytes != dst.buffer.stage_bytes:
                raise CodegenError(
                    f"add 的源和目的单 stage 字节数必须相同（目的 {dst.buffer.name} 为 {dst.buffer.stage_bytes}B），"
                    "否则会读过较短的 buffer"
                )
        self._require_f32(dst, "add")
        self._require_vl(dst)
        lines = self._war_wait(dst.buffer, k, signature, waited)
        ptrs = [self._buf_ptr(dst, k)] + [self._buf_ptr(s, k) for s in stmt.srcs]
        lines.append(f"add_vf({ptrs[1]}, {ptrs[2]}, {ptrs[0]}, {dst.buffer.elems});")
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _emit_leakyrelu(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        dst = stmt.dst
        src = stmt.srcs[0]
        if not isinstance(src, BufRef) or src.buffer.elems != dst.buffer.elems or src.buffer.dtype is not DType.f32:
            raise CodegenError("leakyrelu 当前只生成 f32，且源和目的元素个数必须相同")
        self._require_f32(dst, "leakyrelu")
        self._require_vl(dst)
        alpha = float(stmt.scalars[0])
        lines = self._war_wait(dst.buffer, k, signature, waited)
        lines.append(
            f"leakyrelu_vf({self._buf_ptr(src, k)}, {self._buf_ptr(dst, k)}, {dst.buffer.elems}, {_f32_literal(alpha)});"
        )
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _emit_cast(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        dst = stmt.dst
        src = stmt.srcs[0]
        if (
            not isinstance(src, BufRef)
            or src.buffer.dtype is not DType.f16
            or dst.buffer.dtype is not DType.f32
            or src.buffer.elems != dst.buffer.elems
        ):
            raise CodegenError("cast 当前只生成 f16 到 f32，且两边元素个数必须相同")
        self._require_vl(dst)
        lines = self._war_wait(dst.buffer, k, signature, waited)
        lines.append(
            f"cast_half_to_float_vf({self._buf_ptr(src, k)}, {self._buf_ptr(dst, k)}, {dst.buffer.elems});"
        )
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _emit_reduce(self, stmt: ComputeStmt, j: int, k: int, signature, waited: set) -> list:
        dst = stmt.dst
        src = stmt.srcs[0]
        if not isinstance(src, BufRef) or src.buffer.dtype is not DType.f32:
            raise CodegenError("repeat_reduce_sum 当前只生成 f32")
        self._require_f32(dst, "repeat_reduce_sum")
        if dst.buffer.elems != 8:
            raise CodegenError("repeat_reduce_sum 的目的 buffer 必须是 8 个 f32，供寄存器归约的 8 个通道写回")
        if src.buffer.elems % 64 != 0:
            raise CodegenError("repeat_reduce_sum 的源元素个数必须是 64 的倍数，对齐 3510 的 VF 长度")
        if src.buffer.stage_bytes > _BURST_LEN_MAX:
            raise CodegenError(
                f"buffer {src.buffer.name} 单 stage {src.buffer.stage_bytes}B 超过搬运上限 {_BURST_LEN_MAX}"
            )
        lines = self._war_wait(dst.buffer, k, signature, waited)
        lines.append(f"reduce_sum_vf({self._buf_ptr(src, k)}, {self._buf_ptr(dst, k)}, {src.buffer.elems});")
        lines.extend(self._release_reads(stmt, j, k, signature))
        return lines

    def _require_f32(self, ref: BufRef, op: str) -> None:
        if ref.buffer.dtype is not DType.f32:
            raise CodegenError(f"{op} 当前只核对了 f32 的 3510 头文件签名")

    def _require_vl(self, ref: BufRef) -> None:
        if ref.buffer.stage_bytes % _REPEAT_BYTES != 0:
            raise CodegenError(
                f"buffer {ref.buffer.name} 单 stage {ref.buffer.stage_bytes}B 不是 {_REPEAT_BYTES}B 的整数倍，"
                "无法对齐 VF 迭代（VL=256B）"
            )

    def _release_reads(self, stmt: ComputeStmt, j: int, k: int, signature) -> list:
        lines = []
        released = set()
        for src in stmt.srcs:
            if src.buffer.name in released:
                continue
            released.add(src.buffer.name)
            if self._last_read.get(src.buffer.name) != j:
                continue
            lines.extend(self._war_notify(src.buffer, k, signature))
        return lines

    def _emit_sync(self, stmt: SyncStmt) -> list:
        pair = (stmt.producer, stmt.consumer)
        base = self._alloc(pair, ("fwd", tuple(sorted(b.name for b in stmt.on))))
        ev = f"EVENT_ID{base}"
        p, q = _PIPE_TO_C[stmt.producer], _PIPE_TO_C[stmt.consumer]
        return [f"asc_sync_notify({p}, {q}, {ev});", f"asc_sync_wait({p}, {q}, {ev});"]


def _reg_helper(op: str, kind: str, c_dtype: str = "f32") -> str:
    ctype, vtype = {
        "f32": ("float", "vector_float"),
        "i32": ("int32_t", "vector_int32_t"),
    }[c_dtype]
    if kind == "reg_binary":
        return (
            f"__simd_vf__ inline void {op}_vf(\n"
            f"    __ubuf__ {ctype}* src0, __ubuf__ {ctype}* src1, __ubuf__ {ctype}* dst, uint32_t data_len)\n"
            "{\n"
            f"    uint16_t one_rep_size = asc_get_vf_len() / sizeof({ctype});\n"
            "    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;\n"
            "\n"
            "    vector_bool vmask;\n"
            f"    {vtype} reg_src0;\n"
            f"    {vtype} reg_src1;\n"
            f"    {vtype} reg_dst;\n"
            "    for (uint16_t i = 0; i < repeat_time; ++i) {\n"
            "        vmask = asc_update_mask_b32(data_len);\n"
            "        asc_load(reg_src0, src0 + i * one_rep_size);\n"
            "        asc_load(reg_src1, src1 + i * one_rep_size);\n"
            f"        asc_{op}(reg_dst, reg_src0, reg_src1, vmask);\n"
            "        asc_store(dst + i * one_rep_size, reg_dst);\n"
            "    }\n"
            "}"
        )
    if kind == "reg_unary":
        return (
            f"__simd_vf__ inline void {op}_vf(\n"
            f"    __ubuf__ {ctype}* src, __ubuf__ {ctype}* dst, uint32_t data_len)\n"
            "{\n"
            f"    uint16_t one_rep_size = asc_get_vf_len() / sizeof({ctype});\n"
            "    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;\n"
            "\n"
            "    vector_bool vmask;\n"
            f"    {vtype} reg_src;\n"
            f"    {vtype} reg_dst;\n"
            "    for (uint16_t i = 0; i < repeat_time; ++i) {\n"
            "        vmask = asc_update_mask_b32(data_len);\n"
            "        asc_load(reg_src, src + i * one_rep_size);\n"
            f"        asc_{'ln' if op == 'log' else op}(reg_dst, reg_src, vmask);\n"
            "        asc_store(dst + i * one_rep_size, reg_dst);\n"
            "    }\n"
            "}"
        )
    return (
        f"__simd_vf__ inline void {op}_vf(\n"
        f"    __ubuf__ {ctype}* src, __ubuf__ {ctype}* dst, uint32_t data_len, {ctype} value)\n"
        "{\n"
        f"    uint16_t one_rep_size = asc_get_vf_len() / sizeof({ctype});\n"
        "    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;\n"
        "\n"
        "    vector_bool vmask;\n"
        f"    {vtype} reg_src;\n"
        f"    {vtype} reg_dst;\n"
        "    for (uint16_t i = 0; i < repeat_time; ++i) {\n"
        "        vmask = asc_update_mask_b32(data_len);\n"
        "        asc_load(reg_src, src + i * one_rep_size);\n"
        f"        asc_{op}(reg_dst, reg_src, value, vmask);\n"
        "        asc_store(dst + i * one_rep_size, reg_dst);\n"
        "    }\n"
        "}"
    )


def _f32_literal(value: float) -> str:
    """bisheng 不接受 0f/1f/3f。整数值必须写成 0.0f/1.0f/3.0f。"""
    text = f"{float(value):.9g}"
    if "." not in text and "e" not in text.lower():
        text += ".0"
    return text + "f"


def _burst(buf) -> int:
    """3510 的搬运 burst_len 单位是字节（ADR 0014：2201 的 32B 块数语义在 3510 上不成立，
    实测 1 burst × 256 只搬 256 字节=64 个 f32）。"""
    if buf.stage_bytes % _BLOCK_BYTES != 0:
        raise CodegenError(f"buffer {buf.name} 单 stage {buf.stage_bytes}B 不是 {_BLOCK_BYTES}B 的整数倍")
    if buf.stage_bytes > _BURST_LEN_MAX:
        raise CodegenError(
            f"buffer {buf.name} 单 stage {buf.stage_bytes}B 超过 asc_copy burst_len 的 uint16_t 上限 "
            f"{_BURST_LEN_MAX}；请减小 tile 或拆分搬运"
        )
    return buf.stage_bytes


def _stmt_refs(stmt) -> list:
    if isinstance(stmt, CopyStmt):
        return [stmt.src, stmt.dst]
    if isinstance(stmt, ComputeStmt):
        return [stmt.dst] + list(stmt.srcs)
    return []


def _stmt_reads(stmt) -> list:
    if isinstance(stmt, CopyStmt):
        return [stmt.src] if isinstance(stmt.src, BufRef) else []
    if isinstance(stmt, ComputeStmt):
        return [s for s in stmt.srcs if isinstance(s, BufRef)]
    return []
