# Accumulate kernel/plugin sources registered by each csrc/ops/<op> directory.
macro(register_direct_launch_op KERNEL_SRCS KERNEL_INCLUDE_DIR PLUGIN_SRCS PLUGIN_INCLUDE_DIR)
    get_filename_component(OP_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME)
    set(_kernel_srcs ${KERNEL_SRCS})
    set(_plugin_srcs ${PLUGIN_SRCS})

    if(ALL_KERNEL_SRCS STREQUAL "")
        set(_updated_kernel_srcs ${_kernel_srcs})
    else()
        set(_updated_kernel_srcs ${ALL_KERNEL_SRCS} ${_kernel_srcs})
    endif()
    if(ALL_PLUGIN_SRCS STREQUAL "")
        set(_updated_plugin_srcs ${_plugin_srcs})
    else()
        set(_updated_plugin_srcs ${ALL_PLUGIN_SRCS} ${_plugin_srcs})
    endif()

    set(_kernel_inc ${CMAKE_CURRENT_SOURCE_DIR}/${KERNEL_INCLUDE_DIR})
    set(_plugin_inc ${CMAKE_CURRENT_SOURCE_DIR}/${PLUGIN_INCLUDE_DIR})
    if(ALL_KERNEL_INCLUDE_DIRS STREQUAL "")
        set(_updated_kernel_incs ${_kernel_inc})
    else()
        set(_updated_kernel_incs ${ALL_KERNEL_INCLUDE_DIRS} ${_kernel_inc})
    endif()
    if(ALL_PLUGIN_INCLUDE_DIRS STREQUAL "")
        set(_updated_plugin_incs ${_plugin_inc})
    else()
        set(_updated_plugin_incs ${ALL_PLUGIN_INCLUDE_DIRS} ${_plugin_inc})
    endif()

    set(ALL_KERNEL_SRCS "${_updated_kernel_srcs}" CACHE INTERNAL "direct-launch kernel sources" FORCE)
    set(ALL_PLUGIN_SRCS "${_updated_plugin_srcs}" CACHE INTERNAL "direct-launch plugin sources" FORCE)
    set(ALL_KERNEL_INCLUDE_DIRS "${_updated_kernel_incs}" CACHE INTERNAL "direct-launch kernel includes" FORCE)
    set(ALL_PLUGIN_INCLUDE_DIRS "${_updated_plugin_incs}" CACHE INTERNAL "direct-launch plugin includes" FORCE)
    message(STATUS "Registered direct-launch op: ${OP_NAME}")
endmacro()
