/* !
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This file is generated by ascendc-ir. DO NOT EDIT MANUALLY.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include "c_api/asc_simd.h"

__global__ __cube__ void mmad_custom(__gm__ half* a, __gm__ half* b, __gm__ float* c)
{
    asc_init();

    __cbuf__ half a_l1[512];
    __cbuf__ half b_l1[512];
    __ca__ half a_l0[512];
    __cb__ half b_l0[512];
    __cc__ float c_l0[1024];

    // prologue i = 0
    asc_copy_gm2l1_nd2nz(a_l1, a, 1, 32, 16, 0, 32, 32, 1, 0);
    asc_copy_gm2l1_nd2nz(b_l1, b, 1, 32, 16, 0, 32, 32, 1, 0);
    asc_sync_notify(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
    asc_sync_wait(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
    asc_copy_l12l0a(a_l0, a_l1, 0, 0, 2, 1, 2, 2);
    asc_sync_notify(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
    asc_copy_l12l0b(b_l0, b_l1, 0, 0, 2, 1, 2, 2);
    asc_sync_notify(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
    asc_sync_notify(PIPE_MTE1, PIPE_M, EVENT_ID0);
    asc_sync_wait(PIPE_MTE1, PIPE_M, EVENT_ID0);
    asc_mmad(c_l0, a_l0, b_l0, 32, 16, 32, 0, true, false, true);
    asc_sync_notify(PIPE_M, PIPE_MTE1, EVENT_ID0);
    asc_sync_notify(PIPE_M, PIPE_MTE1, EVENT_ID1);
    // peeled i = 1
    asc_sync_wait(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
    asc_copy_gm2l1_nd2nz(a_l1, a + 16, 1, 32, 16, 0, 32, 32, 1, 0);
    asc_sync_wait(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
    asc_copy_gm2l1_nd2nz(b_l1, b + 16, 1, 32, 16, 0, 32, 32, 1, 0);
    asc_sync_notify(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
    asc_sync_wait(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
    asc_sync_wait(PIPE_M, PIPE_MTE1, EVENT_ID0);
    asc_copy_l12l0a(a_l0, a_l1, 0, 0, 2, 1, 2, 2);
    asc_sync_wait(PIPE_M, PIPE_MTE1, EVENT_ID1);
    asc_copy_l12l0b(b_l0, b_l1, 0, 0, 2, 1, 2, 2);
    asc_sync_notify(PIPE_MTE1, PIPE_M, EVENT_ID0);
    asc_sync_wait(PIPE_MTE1, PIPE_M, EVENT_ID0);
    asc_sync_pipe(PIPE_M);
    asc_mmad(c_l0, a_l0, b_l0, 32, 16, 32, 0, true, false, false);
    // 循环之后
    asc_sync_notify(PIPE_M, PIPE_FIX, EVENT_ID0);
    asc_sync_wait(PIPE_M, PIPE_FIX, EVENT_ID0);
    asc_set_l0c2gm_nz2nd(1, 0, 0);
    asc_copy_l0c2gm(c, c_l0, 32, 32, 32, 32, 0, 0, 0, false, true);
}

#include "op_mmad_launch.h"

extern "C" void launch_op_mmad(GM_ADDR a, GM_ADDR b, GM_ADDR c, void* stream)
{
    mmad_custom<<<1, 0, stream>>>((__gm__ half*)a, (__gm__ half*)b, (__gm__ float*)c);
}
