/* !
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This file is generated by ascendc-ir. DO NOT EDIT MANUALLY.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include "c_api/asc_simd.h"

__simd_vf__ inline void reduce_sum_vf(
    __ubuf__ float* x_local, __ubuf__ float* y_local, uint32_t data_len)
{
    uint16_t one_rep_size = asc_get_vf_len() / sizeof(float);
    uint16_t repeat_time = (data_len + one_rep_size - 1) / one_rep_size;

    vector_bool vmask;
    vector_float src_reg;
    vector_float dst_reg;
    vector_float acc_reg;
    asc_duplicate_scalar(acc_reg, 0.0f);
    for (uint16_t i = 0; i < repeat_time; ++i) {
        vmask = asc_update_mask_b32(data_len);
        asc_loadalign(src_reg, x_local + i * one_rep_size);
        asc_reduce_sum(dst_reg, src_reg, vmask);
        asc_add(acc_reg, acc_reg, dst_reg, vmask);
    }
    asc_storealign(y_local, acc_reg, vmask);
}

__vector__ __global__ __aicore__ void op_repeat_reduce_sum(__gm__ float* x, __gm__ float* z)
{
    asc_init();

    __ubuf__ float buf_0[64];
    __ubuf__ float buf_1[8];

    asc_copy_gm2ub(buf_0, x, 1, 256, 0, 0);
    asc_sync_notify(PIPE_MTE2, PIPE_V, EVENT_ID0);
    asc_sync_wait(PIPE_MTE2, PIPE_V, EVENT_ID0);
    reduce_sum_vf(buf_0, buf_1, 64);
    asc_sync_notify(PIPE_V, PIPE_MTE3, EVENT_ID0);
    asc_sync_wait(PIPE_V, PIPE_MTE3, EVENT_ID0);
    asc_copy_ub2gm(z, buf_1, 1, 32, 0, 0);
}

#include "op_repeat_reduce_sum_launch.h"

extern "C" void launch_op_repeat_reduce_sum(GM_ADDR x, GM_ADDR z, void* stream)
{
    op_repeat_reduce_sum<<<1, 0, stream>>>((__gm__ float*)x, (__gm__ float*)z);
}
